"""
Backward compatibility wrapper for DataManager.

This module provides a DataManager class that maintains the same interface
as the original but uses the new service-oriented architecture internally.
"""

import logging
from ..api.api_factory import create_api_provider
from .retrieval_service import PaperRetrievalService
from .validation_service import DataValidationService
from .data_coordinator import DataCoordinator
from .frame_manager import FrameManager
from ..graph import GraphManager, GraphProcessing
from ArticleCrawler.papervalidation.retraction_watch_manager import RetractionWatchManager

class DataManager:
    """
    Backward compatibility wrapper for the original DataManager.
    
    This class maintains the exact same interface as the original DataManager
    but delegates all operations to the new service-oriented architecture.
    Existing code using DataManager will continue to work without changes.
    """
    
    def __init__(self, 
                 paper_id_seed=None, 
                 crawl_initial_condition=None, 
                 reporting_options=None, 
                 graph_options=None,
                 data_storage_options=None, 
                 retraction_options=None, 
                 logger=None, 
                 frames=None,
                 api_provider_type='openalex',
                 api_provider_kwargs=None):
        
        if logger is not None:
            self.logger = logger
        elif data_storage_options is not None:
            from ArticleCrawler import CrawlerLogger
            self.logger = CrawlerLogger(data_storage_options)
        else:
            self.logger = logging.getLogger("DataManagerLogger")
            logging.basicConfig(level=logging.INFO)

        # Handle backward compatibility for initial conditions
        self.crawl_initial_condition = crawl_initial_condition
        if self.crawl_initial_condition is None:
            self.paper_id_seed = paper_id_seed
            self.logger.info("Use crawl_initial_condition generated by CrawlerParameter for DataManager.")
        else:
            self.paper_id_seed = self.crawl_initial_condition.seed_paperid
            if paper_id_seed is not None: 
                self.logger.info("Paper_id_seed provided to DataManager is ignored, crawl_initial_condition is used instead.")

        api_kwargs = api_provider_kwargs or {}
        api_kwargs['logger'] = self.logger
        api_provider = create_api_provider(api_provider_type, **api_kwargs)

        retrieval_service = PaperRetrievalService(api_provider, self.logger)
        validation_service = DataValidationService(self.logger)
        
        frame_manager = frames or FrameManager(
            reporting_options=reporting_options,
            data_storage_options=data_storage_options,
            logger=self.logger
        )

        retraction_watch_manager = RetractionWatchManager(
            storage_and_logging_options=data_storage_options,
            retraction_options=retraction_options, 
            logger=self.logger
        )

        graph_manager = GraphManager(
            reporting_options=reporting_options, 
            graph_options=graph_options, 
            logger=self.logger
        )
        
        graph_processing = GraphProcessing(data_manager=self, logger=self.logger)

        self._coordinator = DataCoordinator(
            retrieval_service=retrieval_service,
            validation_service=validation_service,
            frame_manager=frame_manager,
            retraction_manager=retraction_watch_manager,
            graph_manager=graph_manager,
            graph_processing=graph_processing,
            crawl_initial_condition=crawl_initial_condition,
            logger=self.logger
        )

        # For backward compatibility, expose coordinator attributes
        self.no_papers_retrieved = self._coordinator.no_papers_retrieved

    # Delegate all methods to the coordinator for backward compatibility
    def __getattr__(self, name):
        """Delegate attribute access to the coordinator."""
        return getattr(self._coordinator, name)

    @property
    def frames(self):
        """Access to frame manager."""
        return self._coordinator.frames

    @property
    def api(self):
        """Access to API provider for backward compatibility."""
        return self._coordinator.retrieval.api

    @property
    def graph(self):
        """Access to graph manager."""
        return self._coordinator.graph

    @property
    def graph_processing(self):
        """Access to graph processing."""
        return self._coordinator.graph_processing

    @property
    def retraction_watch_manager(self):
        """Access to retraction watch manager."""
        return self._coordinator.retraction_manager